baseURL = "https://egonelbre.com"
languageCode = "en-us"
title = "Egon Elbre"
canonifyURLs = false
theme = "clean"

pagination.pagerSize = 20

pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsoptions = "linenos=true"

copyright = "Egon Elbre 2019"
disqusShortname = ""

pluralizeListTitles = false

[markup.goldmark.renderer]
  unsafe=true

[social]
  bluesky = "egonelbre"

[params.assets]
  customCSS = []

[params.social]
  bluesky   = "egonelbre"
  github    = "egonelbre"
  # email     = "egonelbre@gmail.com"
  linkedin  = "egonelbre"
  instagram = "egonelbre"
  gallery   = "https://gallery.egonelbre.com"
  soundcloud = "egon-elbre"
  rss       = "index.xml"
[params.social.config]
  platforms = ["bluesky","github","email","linkedin","instagram","gallery","soundcloud","rss"]

[params.rss]
  authorName = "Egon Elbre"

[permalinks]
	writing = "/:title/"
	projects = "/project/:title/"
	code = "/code/:title/"

[menu]
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    title = "My writing on various topics."
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Fleshed out projects."
    url = "/projects/"
    weight = 2
  [[menu.main]]
    identifier = "code"
    name = "Code"
    title = "Interesting code snippets and experiments."
    url = "/code/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 4
