baseURL = "http://egonelbre.com"
languageCode = "en-us"
title = "Egon Elbre"
canonifyURLs = false
theme = "clean"

paginate = 10

pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsoptions = "linenos=true"

copyright = "&copy; Egon Elbre 2019"
disqusShortname = ""
googleAnalytics = ""

pluralizeListTitles = false

[menu]
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    title = "Longer and more thought out writing."
    url = "/articles/"
	weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Writing on easy topics."
    url = "/blog/"
	weight = 2
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Fleshed out projects."
    url = "/projects/"
	weight = 3
  [[menu.main]]
    identifier = "code"
    name = "Code"
    title = "Interesting code snippets and experiments."
    url = "/code/"
	weight = 4

[taxonomies]
	tag  = "tags"
	blog = "blog"
	code = "code"

[permalinks]
	articles = "/:title/"
	blog = "/:title/"
	projects = "/:title/"
	code = "/code/:title/"
