baseURL = "http://egonelbre.com"
languageCode = "en-us"
title = "Egon Elbre"
canonifyURLs = false
theme = "clean"

paginate = 40

pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsoptions = "linenos=true"

copyright = "&copy; <a href=\"https://egonelbre.com\">Egon Elbre</a> 2019"
disqusShortname = ""
googleAnalytics = ""

[permalinks]
	article = "/:title/"
	blog = "/:title/"
	project = "/:title/"
	code = "/code/:title/"
