baseURL = "http://egonelbre.com"
languageCode = "en-us"
title = "Egon Elbre"
canonifyURLs = false
theme = "clean"

[permalinks]
	blog = "/blog/:title/"
	code = "/code/:title/"
	project = "/project/:title/"
