baseURL = "http://egonelbre.com"
languageCode = "en-us"
title = "Egon Elbre"
canonifyURLs = false
theme = "clean"

paginate = 40

[permalinks]
	article = "/:title/"
	blog = "/:title/"
	project = "/:title/"
	code = "/code/:title/"
